"""add country, year, genre

Revision ID: 13511506c865
Revises: 190b6b5b9fff
Create Date: 2020-05-28 22:26:40.809133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13511506c865'
down_revision = '190b6b5b9fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('country', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('genre', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('year', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'year')
    op.drop_column('post', 'genre')
    op.drop_column('post', 'country')
    # ### end Alembic commands ###
