"""список киношек

Revision ID: 43ff49e81804
Revises: acdaf871822e
Create Date: 2020-05-31 14:54:28.985000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ff49e81804'
down_revision = 'acdaf871822e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('tag', sa.Column('time', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'time')
    op.drop_column('tag', 'location')
    # ### end Alembic commands ###
